profile:
  name: full
  description: Full physical rover stack for normal operation.

components:
  base: true
  odometry: true
  description: true
  localization: true
  twist_mux: true
  imu: true
  lidar: true
  led_strip: true
  web: true
  display: true
  rosboard: true

  octoliner: false
  waveshare_audio: false
  camera: false
  vision: false
